# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RCloudDemo' do
    pod 'RongCloudIM/IMLib'
    pod 'Masonry'
    pod 'SDWebImage'
end

target 'RCloudDemoTests' do
    pod 'Expecta'
end

